Edited lint and build/test pipelines

diff --git a/.github/workflows/docker-build-generator.yml b/.github/workflows/docker-build-generator.yml
--- a/.github/workflows/docker-build-generator.yml
+++ b/.github/workflows/docker-build-generator.yml
@@ -16,8 +16,70 @@ env:
 
 
 jobs:
-  build:
+  test:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
 
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    - name: Build Docker image
+      run: |
+        docker build -t test-container src/generator
+
+    - name: Run the Docker container
+      run: |
+        docker run -d \
+          -p 8010:8010 \
+          --name test-container test-container
+
+    - name: Wait the container to be up and running
+      run: |
+        sleep 10
+
+    - name: Check container status
+      run: |
+        if ! docker inspect test-container >/dev/null 2>&1; then
+         echo "Container does not exist."
+         exit 1
+        fi
+
+        STATUS=$(docker inspect --format='{{.State.Status}}' test-container)
+
+        if [ "$STATUS" != "running" ]; then
+         echo "Container is not running. Status: $STATUS"
+         echo "==== Container Logs ===="
+         docker logs test-container  # Print logs for debugging
+         exit 1  # Fail the pipeline
+        fi
+
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pytest
+        pip install -r src/model_registry/test/requirements.txt
+
+    - name: Run GENERATOR tests
+      run: pytest src/generator/test/
+
+    - name: Run SERVER tests
+      run: pytest src/test
+
+    - name: Stop and remove container
+      run: |
+        docker stop test-container
+        docker rm test-container
+  
+
+  build:
+    needs: test
     runs-on: ubuntu-latest
     permissions:
       contents: read
