edited pipeline

diff --git a/.github/workflows/docker-build-middleware.yml b/.github/workflows/docker-build-middleware.yml
--- a/.github/workflows/docker-build-middleware.yml
+++ b/.github/workflows/docker-build-middleware.yml
@@ -100,13 +100,19 @@ jobs:
           sleep 10
 
       - name: Check container status
-        run: |      
-          STATUS=$(docker inspect --format='{{.State.Status}}' test-container || echo "not_found")
+        run: |
+          if ! docker inspect test-container >/dev/null 2>&1; then
+           echo "Container does not exist."
+           exit 1
+          fi
+
+          STATUS=$(docker inspect --format='{{.State.Status}}' test-container)
           
           if [ "$STATUS" != "running" ]; then
-            echo "Container failed to start (status: $STATUS)"
-            docker logs test-container  # Print logs for debugging
-            exit 1  # Fail the pipeline
+           echo "Container is not running. Status: $STATUS"
+           echo "==== Container Logs ===="
+           docker logs test-container  # Print logs for debugging
+           exit 1  # Fail the pipeline
           fi
 
       - name: Stop and remove container
